<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Incidents Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Incidents Export Report</h1>
        <p>Generated on: {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Title</th>
                <th>Event Type</th>
                <th>Severity</th>
                <th>Status</th>
                <th>Department</th>
                <th>Reported By</th>
                <th>Assigned To</th>
                <th>Incident Date</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            @foreach($incidents as $incident)
            <tr>
                <td>{{ $incident->reference_number }}</td>
                <td>{{ $incident->title ?? $incident->incident_type }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $incident->event_type ?? 'N/A')) }}</td>
                <td>{{ ucfirst($incident->severity ?? 'N/A') }}</td>
                <td>{{ ucfirst($incident->status ?? 'N/A') }}</td>
                <td>{{ $incident->department?->name ?? 'N/A' }}</td>
                <td>{{ $incident->reporter?->name ?? $incident->reporter_name ?? 'N/A' }}</td>
                <td>{{ $incident->assignedTo?->name ?? 'N/A' }}</td>
                <td>{{ $incident->incident_date ? $incident->incident_date->format('Y-m-d') : 'N/A' }}</td>
                <td>{{ $incident->location ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Incidents: {{ $incidents->count() }}</p>
        <p>This report was generated by the HSE Management System</p>
    </div>
</body>
</html>

