@extends('layouts.app')

@section('title', 'PPE Compliance Report')

@section('content')
<div class="bg-white shadow-sm border-b">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-4">
            <div class="flex items-center space-x-3">
                <a href="{{ route('ppe.reports.index') }}" class="text-gray-600 hover:text-gray-700">
                    <i class="fas fa-arrow-left mr-2"></i>Back
                </a>
                <h1 class="text-2xl font-bold text-gray-900">Compliance Report: {{ $report->reference_number }}</h1>
            </div>
        </div>
    </div>
</div>

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="bg-white rounded-lg shadow p-6 mb-6">
        <h2 class="text-lg font-semibold text-gray-900 mb-4">Report Summary</h2>
        <dl class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <dt class="text-sm font-medium text-gray-500">Report Type</dt>
                <dd class="mt-1 text-sm text-gray-900">{{ ucfirst(str_replace('_', ' ', $report->report_type)) }}</dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">Period</dt>
                <dd class="mt-1 text-sm text-gray-900">{{ $report->report_period_start->format('M d, Y') }} - {{ $report->report_period_end->format('M d, Y') }}</dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">Scope</dt>
                <dd class="mt-1 text-sm text-gray-900">{{ ucfirst($report->scope) }}</dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">Generated By</dt>
                <dd class="mt-1 text-sm text-gray-900">{{ $report->generatedBy->name ?? 'N/A' }}</dd>
            </div>
        </dl>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-sm text-gray-600">Total Issuances</p>
            <p class="text-3xl font-bold text-gray-900 mt-2">{{ $report->total_issuances }}</p>
        </div>
        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-sm text-gray-600">Active Issuances</p>
            <p class="text-3xl font-bold text-green-600 mt-2">{{ $report->active_issuances }}</p>
        </div>
        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-sm text-gray-600">Compliance Rate</p>
            <p class="text-3xl font-bold {{ $report->compliance_rate >= 90 ? 'text-green-600' : ($report->compliance_rate >= 70 ? 'text-yellow-600' : 'text-red-600') }} mt-2">
                {{ number_format($report->compliance_rate, 1) }}%
            </p>
        </div>
        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-sm text-gray-600">Non-Compliant</p>
            <p class="text-3xl font-bold text-red-600 mt-2">{{ $report->non_compliant_count }}</p>
        </div>
    </div>

    @if($report->summary)
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-lg font-semibold text-gray-900 mb-4">Summary</h2>
        <p class="text-gray-700">{{ $report->summary }}</p>
    </div>
    @endif
</div>
@endsection

