<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Risk Assessments Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Risk Assessments Export Report</h1>
        <p>Generated on: {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Title</th>
                <th>Assessment Type</th>
                <th>Risk Level</th>
                <th>Risk Score</th>
                <th>Severity</th>
                <th>Likelihood</th>
                <th>Status</th>
                <th>Department</th>
                <th>Created By</th>
                <th>Assigned To</th>
                <th>Assessment Date</th>
                <th>Next Review Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assessments as $assessment)
            <tr>
                <td>{{ $assessment->reference_number }}</td>
                <td>{{ $assessment->title }}</td>
                <td>{{ ucfirst($assessment->assessment_type ?? 'N/A') }}</td>
                <td>{{ ucfirst($assessment->risk_level ?? 'N/A') }}</td>
                <td>{{ $assessment->risk_score ?? 'N/A' }}</td>
                <td>{{ ucfirst($assessment->severity ?? 'N/A') }}</td>
                <td>{{ ucfirst($assessment->likelihood ?? 'N/A') }}</td>
                <td>{{ ucfirst($assessment->status ?? 'N/A') }}</td>
                <td>{{ $assessment->department?->name ?? 'N/A' }}</td>
                <td>{{ $assessment->creator?->name ?? 'N/A' }}</td>
                <td>{{ $assessment->assignedTo?->name ?? 'N/A' }}</td>
                <td>{{ $assessment->assessment_date ? $assessment->assessment_date->format('Y-m-d') : 'N/A' }}</td>
                <td>{{ $assessment->next_review_date ? $assessment->next_review_date->format('Y-m-d') : 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Risk Assessments: {{ $assessments->count() }}</p>
        <p>This report was generated by the HSE Management System</p>
    </div>
</body>
</html>

